---
- name: Deploys phycom app to a server
  hosts: "{{ hosts }}"
  gather_facts: no
  vars:
    ansistrano_deploy_via: git
    # Set your real repository here
    ansistrano_git_repo: git@github.com:99com/phycom-template.git
    ansistrano_git_branch: "{{ branch }}"
    # Set this to the destination where the app will be deployed on remote server
    ansistrano_deploy_to: "{{ deploy_root }}"
    ansistrano_keep_releases: 3
    ansistrano_shared_paths:
      - logs
      - files
    ansistrano_shared_files:
      - config.php
    ansistrano_allow_anonymous_stats: No
    ansistrano_before_symlink_tasks_file: deploy-hooks/before-symlink.yml
    ansistrano_before_cleanup_tasks_file: deploy-hooks/before-cleanup.yml
    ansistrano_after_symlink_tasks_file: deploy-hooks/after-cleanup.yml
  roles:
    - ansistrano.deploy
